# Query-only profile configuration
druid:
  mcp:
    tools:
      enabled:
        - "listDatasources"
#        - "showDatasourceDetails"
#        - "listLookups"
#        - "getLookupsForTier"
#        - "getLookup"
#        - "getLookupStatus"
#        - "getLookupStatusForTier"
        - "queryDruidSql"
#        - "viewAllCompactionConfigs"
#        - "viewCompactionConfigForDatasource"
#        - "viewCompactionConfigHistory"
#        - "viewCompactionStatus"
#        - "viewCompactionStatusForDatasource"
#        - "viewAllRetentionRules"
#        - "viewRetentionRulesForDatasource"
#        - "viewRetentionRuleHistory"
#        - "listAllSegments"
#        - "getSegmentsForDatasource"
#        - "getSegmentsWithDetailsForDatasource"
#        - "getSegmentDetails"
#        - "getSegmentMetadata"
#        - "getSegmentMetadataForDatasource"
#        - "getLoadQueueStatus"
#        - "listSupervisors"
#        - "getSupervisorStatus"
#        - "listRunningTasks"
#        - "listPendingTasks"
#        - "listWaitingTasks"
#        - "listCompletedTasks"
#        - "getTaskStatus"
#        - "getTaskReports"
#        - "getTaskLog"
#        - "listAuthenticationUsers"
#        - "getAuthenticationUser"
#        - "listAuthorizationUsers"
#        - "getAuthorizationUser"
#        - "listRoles"
#        - "getRole"
#        - "getAuthenticatorChainAndAuthorizers"
